name: clean_arhitecture
description: A new Flutter project.



version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  dartz: ^0.10.1

  #state managment
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  #Network
  dio: ^5.3.3
  retrofit: ^4.0.3
  internet_connection_checker: ^1.0.0+1
  get_it: ^7.6.4
  pretty_dio_logger: ^1.3.1
  lottie: ^2.6.0
  another_flushbar: ^1.12.30







dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^1.0.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  copy_with_extension_gen: ^5.0.4
  retrofit_generator: ^8.0.1
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/json/
    - assets/translations/